name: ambu_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # flutter_localization: ^0.2.0
  intl: ^0.18.1
  path_provider: ^2.1.2
  geolocator: ^11.0.0
  cached_network_image: ^3.3.1
#  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  ionicons: ^0.2.2
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.7.0
  fluttertoast:
  url_launcher: ^6.2.6
  google_maps_flutter: ^2.6.0
  # intl: ^0.19.0
#  google_maps: ^7.1.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
#  flutter_polyline_points: ^2.0.0
  flutter_search_bar: ^3.0.0
#  permission_handler: ^11.3.1
  google_nav_bar: ^5.0.6
  curved_navigation_bar: ^1.0.3
  connectivity_wrapper: ^1.1.4
  flutter_bloc: ^8.1.5
  connectivity_plus: ^5.0.1
  internet_connection_checker: ^1.0.0+1
  # flutter_sms: ^2.3.3

  
  
  # carousel_slider: ^4.2.1

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  firebase_core: ^2.29.0
  firebase_messaging: ^14.7.20
  location: ^6.0.1
#  flutter_map: ^6.1.0
#  latlong2: ^0.9.1
  flutter_joystick: ^0.0.4
#  gebetamap: any
  flutter_map: ^4.0.0
  gebetamap: ^1.1.4
#  flutter_osm_plugin: ^0.70.4
  permission_handler: ^11.0.1
#  flutter_osm_plugin: ^0.60.4
  flutter_osm_plugin: 0.70.1

  latlong2: ^0.8.2
#  webview_flutter: ^4.7.0\

#  flutter_map: any
  # dropdown_search: ^5.0.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  # path_provider: ^2.1.2

  flutter_lints: ^3.0.0
  get:

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/
    - icons/